version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "part: github_actions"

  - updates:
      - package-ecosystem: "uv"
        directory: "/"
        schedule:
          interval: "weekly"
